embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.7
reg_weight: [1e-04]

cf_model: lightgcn
mess_dropout: [0.1, 0.1]
loss_ratio: [0.03]
norm_type: sym
n_layers: 1
knn_k: 10

learning_rate: [0.01]

hyper_parameters: ["reg_weight", "learning_rate","loss_ratio"]

