recdim: 64
layer_num: 3
reg: [0.0001, 0.001, 0.01, 0.1]
ssl_task: 'FAC'
learning_rate: [0.0001, 0.001, 0.01, 0.1]
weight_decay: 1e-4
ssl_alpha: [0.01, 0.05, 0.1, 0.5, 1.0]
ssl_temp: [0.1, 0.2, 0.5, 1.0]
dropout_rate: 0.3
mm_fusion_mode: 'concat'
temp: 0.2
init: 'xavier'
adj_type: 'pre'
hyper_parameters: ["learning_rate", "ssl_temp", "ssl_alpha", "reg"]

#
#[hyperparameters]
#layer_num=3
#reg=1e-4
#ssl_mode=both
#description="Go SLMRec"
#batch_size=2048
#recdim=64
#temp=0.2
#dropout_rate=0.3
#testbatch=128
#test_step=1
#stop_cnt=50
#dataset=movielens
#path=./checkpoints
#topks=[10]
#num_epoch=1000
#multicore=0
#pretrain=0
#seed=2021
#is_load_test_dataset=1
#train_type=normal
#verbose=1
#init=xavier
#optim=adam
#save_flag=False
#adj_type=pre
#
#ssl_task=FAC
#lr=0.01
#weight_decay=1e-4
#ssl_alpha=0.1
#ssl_temp=0.2
#loss=multi_loss
